### ISSUE TITLE
RHS position 1 truncated (precision lost) when assigning to type 'integer' (column 5 named 'Intensity')

### ISSUE THREAD

**Issue by jfbourdon** [Jean-Romain/MFFProads#15]
Avertissement apparu une seule fois sur près de 900 km de chemin. Pas l'impression que c'est particulièrement important. Peut-être que tous les messages liés à l'intensité pourraient être supprimés sauf si la colonne est inexistante.

Données: https://transfert.mffp.gouv.qc.ca/?ShareToken=2A6B76617A42B6BE7C206CFBA3913D3BD9928EDC

```
Warning message:
In `[.data.table`(nlas@data, Intensity > 2 * q, `:=`(Intensity,  :
  1478.120000 (type 'double') at RHS position 1 truncated (precision lost) when assigning to type 'integer' (column 5 named 'Intensity')
```

Je pense à ça et il pourrait être pertinent d'avoir une option dans `measure_road` pour de pas utiliser les valeurs d'intensité dans l'évaluation des routes. On a probablement des contrats où les valeurs d'intensités sont tout croche ce qui pourrait nuire à l'analyse.

**Comment by Jean-Romain** [comment]
Ok je sais pas si je vais regarder ca de facon non urgente.

Sinon je suis d'accord pour une option `no_intensity`

**Comment by Jean-Romain** [comment]
Corrigé + si l'intensité n'est pas chargée alors l'intensité pas utilisée
```r
ctg  <- readLAScatalog("point_cloud.laz", select = "* -i")
```
