### ISSUE TITLE
no non-missing arguments to max; returning -Inf

### ISSUE THREAD

**Issue by jfbourdon** [Jean-Romain/MFFProads#16]
Présent à la fois sur c6155e5 et 36815f2 (avant correctif pour #5) lors de l'utilisation de `measure_road()` avec les paramètres par défaut.
Données: https://transfert.mffp.gouv.qc.ca/?ShareToken=B664D3220AFD1F4AAD82C135F4A479F3DA64562F

**Comment by Jean-Romain** [comment]
Pas reproductible. Je pense avoir corrigé ca dans #17 où j'ai corrigé bcp de chose.

Encore une route mal trouvée. Je met un label pour plus tard
