### ISSUE TITLE
some indices are invalid (NA returned)

### ISSUE THREAD

**Issue by jfbourdon** [Jean-Romain/MFFProads#17]
Avertissement lors de l'utilisation de `measure_road()` avec les paramètres par défaut. Avant le message final, il y a d'autres avertissements à propos de _points non normalisables et retirés_.
Données: https://transfert.mffp.gouv.qc.ca/?ShareToken=367F2B921C667189A1A5321B048F3ADA38AF4EDA

```
Warning message:
In .doExtract(x, i, drop = drop) : some indices are invalid (NA returned)
```

**Comment by Jean-Romain** [comment]
Tous ces cas speciaux qui tombent à des endroits où il y a pas de points, pas assez de point, des points sauf à un endroit critique ou je ne sais quoi sont horrible à débugger
