### ISSUE TITLE
Ajout d'un métrique d'écart entre la route originale et la route corrigée

### ISSUE THREAD

**Issue by jfbourdon** [Jean-Romain/MFFProads#22]
Parfois, certaines routes parallèles sont repositionnées l'une par-dessus l'autre et il devient difficile d'identifier ces cas car l'attribut `STATE` peut quand même être `1`. La vérification de l'endroit où passe le segment corrigé dans les _end caps_ visait à aider à identifier ces cas (PR #21), mais ce n'est pas parfait. J'ai donc pensé à un autre attribut qui donnerait un coup de pouce supplémentaire.

En gros, il s'agit de calculer l'aire du polygone formé par la jonction du segment original avec le segment corrigé divisé par la longueur du segment corrigé. Plus ce ratio est grand, plus la modification a été majeure et mérite une attention particulière.

Dans l'exemple ci-dessous, le segment en rouge est l'original et en vert le corrigé (pour qui `STATE` = `1` car il a été repositionné sur une belle route adjacente). Le ratio donne 143.8 m²/m, ce qui est énorme comparé à un segment adéquatement repositionné qui devrait peut-être avoir 10 m²/m au plus.

![ecart](https://user-images.githubusercontent.com/32580398/143475042-725b4885-116d-4c79-afdf-b30763fde802.png)

```r
library(sf)
library(dplyr)
library(ggplot2)


measure_change <- function(road_ori, road_cor, graph = FALSE)
{
  # Extraction des coordonnées
  coords_ori <- sf::st_coordinates(road_ori)[,-3]
  coords_cor <- sf::st_coordinates(road_cor)[,-3]
  
  
  # Ajustement des coordonnées pour pouvoir
  # constituer une suite de vertex valides
  # pour un polygone et m'assurer que le
  # polygone est fermé
  m_dist <- c(dist(rbind(coords_ori[1,], coords_cor[1,]))[1],
              dist(rbind(coords_ori[1,], coords_cor[nrow(coords_cor),]))[1])

  closest_vertex <- which.min(m_dist)
  
  if (closest_vertex == 1)
  {
    coords_cor[,1] <- rev(coords_cor[,1])
    coords_cor[,2] <- rev(coords_cor[,2])
  }
  
  coords_cor <- rbind(coords_cor,
                     c(coords_ori[1,1], coords_ori[1,2]))
  
  
  # Construction du polygone
  coords_poly <- rbind(coords_ori, coords_cor)
  poly <- sf::st_sfc(sf::st_polygon(list(coords_poly)),
                     crs = sf::st_crs(road_ori))
  
  # Indice d'écart
  # Plus la valeur est grande, plus la différence est grande
  # entre le segment d'origine et celui corrigé
  ratio <- as.numeric(sf::st_area(poly) / sf::st_length(road_cor))
  
  
  # Représentation graphique des différences
  if (graph)
  {
    print(
      ggplot2::ggplot() +
        ggplot2::geom_sf(data = poly, fill = "orange") +
        ggplot2::geom_sf(data = road_ori, size = 1, color = "red") +
        ggplot2::geom_sf(data = road_cor, size = 1, color = "darkgreen")
    )
    
    message("Écart par rapport au segment original: ", sprintf("%.1f", ratio), " m²/m")
  }
  
  return(ratio)
}


# Exemple pour quatre segments d'une intersection à partir des
# données de https://github.com/Jean-Romain/MFFProads/files/7600537/dataset.zip
roads_ori <- sf::st_read("dataset.gpkg", "original")
roads_cor <- sf::st_read("dataset.gpkg", "corrected")

for(k in c(3, 30, 233, 314))
{
  measure_change(roads_ori[k,], roads_cor[k,], graph = TRUE)
}
```

Je me questionne à savoir si le ratio ne devrait pas être plutôt `aire polygone / longueur segment original` au lieu de `aire polygone / longueur segment corrigé` ou encore une autre combinaison, mais il y a définitivement quelque chose à faire avec ça. Toutefois, je n'utiliserais pas la valeur de cet indice pour pondérer `SCORE` ou `STATE`, je le verrais vraiment comme un attribut à utiliser uniquement par l'utilisateur.

**Comment by Jean-Romain** [comment]
Tu cherches des solutions pour détecter des problèmes et je crois qu'on devrait chercher des solutions pour résoudre le problème. Ce genre de problème je pensais, d'après mon jeu d’entraînement, qu'ils étaient rare. Je connaissais le problème et je vous l'ai mentionné dans ma présentation mais si il est trop fréquent il faut le résoudre.

Le problème c'est que ce problème est inhérent à la méthode. Une idée qui me vient en tête serait de faire plusieurs passes avec plusieurs buffers de tailles croissantes et de garder la route avec le meilleur SCORE et la plus proche géométriquement de la référence. On pourrait utiliser ton score pour le dernier point. Mais je crois qu'il faudrait plutôt chercher du cote de la notion de congruance.

Une autre solution envisageable c'est de splitter la route en petits morceaux. C'est déjà le cas en fait mais pour les très longues routes mais essentiellement pour des raisons d'utilisation mémoire et de temps de calcul. Peut être que changer ca peut aider

```
mffproads_default_parameters$extraction$road_max_len
```

Il y a d'autre paramètre qu'on peut changer pour trouver la route. Mais il faudrait que ça marche pour TOUTES les routes.

**Comment by jfbourdon** [comment]
C'est pas si fréquent, mais ce que je veux éviter c'est qu'on diffuse une couche où il y a certains segments qui sont vraiment pire qu'avant, même si ça ne présente pas un gros pourcentage. Mais oui c'est certain que le mieux ce serait corriger le problème à la source. Mon idée pour tout de suite était d'utiliser ma proposition pour corriger manuellement ces tronçons problématiques.

Toutefois, comme tu le proposes, il pourrait y avoir une phase d'optimisation utilisant mon score. Si la première passe donne un indice en-deçà d'un certain seuil on ne va pas plus loin, mais sinon tu fais une autre passe avec un buffer plus petit et tu vérifies de nouveau si une autre passe est nécessaire jusqu'à une certaine limite.

**Comment by Jean-Romain** [comment]
> il y a certains segments qui sont vraiment pire qu'avant, même si ça ne présente pas un gros pourcentage.

Le problème c'est qu'il y aura toujours des cas où ça marche pas surtout sur avec des dizaine de milliers de segments. Et quand ça marche pas ça sera toujours pire que l'original parce que l'original est tout à fait correct. 

Donc oui tu as raisons mettre des warning et des notes à l'output serait pertinent. Ce que je n'aime pas avec ce que tu proposes c'est que ça sort de nulle part. Ca à l'air bien quand on regarde vite c'est vrai mais en pratique quelle sont les propriétés de ta méthode ? Par exemple que se passe t'il si les lignes s'entrecroisent et que le polygone n'est pas une *simple feature* valide ? Je vais tester avec les données que tu m'as envoyé pour voir si il y a des cas comme ca.

 Mai je suis certain qu'il existe des méthodes éprouvées dont on connaît bien les propriétés pour faire ca que j'aimerai mieux tester avant de créer quelque chose de custom.

**Comment by jfbourdon** [comment]
Tu as bien compris pourquoi je cherche à ce point à mettre des warnings partout :) . Quand je lancerai ça sur des centaines de milliers d'entités, il faut absolument qu'on puisse ensuite faire un tri entre ce qui est fort probablement assez bon et le reste qui demandera un coup d'œil humain rapide. D'ailleurs à ce propos, je vais m'arranger pour grossir bientôt mon jeu de données pour avoir au moins 5000 entités et couvrir encore plus de cas bizarres.

Concernant ma méthode, ça semble sortir de nulle part, mais en fait ça revient essentiellement à faire la différence de l'intégrale de deux équations (un segment de route étant ici simplement plusieurs fonctions bornées). Si j'ai `y = x²` et `y = x`, l'écart entre les deux courbe (donc l'aire) correspondra à `y = x³/3 - x²/2` et avec ma méthode je divise par la longueur d'une des deux fonctions. J'imagine qu'il doit exister des méthodes autres pour comparer la similitude entre deux fonctions. Il y a probablement moyen de calculer une sorte de moindres carrés entre un segment comme référence et un deuxième comme étant des observations (en établissant sa coordonnées en Y à intervalle de 1 m en X par exemple).

Pour ce qui est des conséquences des entrecroisements, ça crée un polygone invalide, mais comme le polygone continue de respecter le sens de fermeture (ce qui est à gauche du sens des vertex est toujours considéré comme étant l'intérieur d'un polygone), on peut quand même calculer une aire qui sera exacte. Même chose s'il y a plusieurs vertex empilés les uns sur les autres, le polygone sera invalide, mais l'aire correcte. Je n'ai pas eu de problèmes sur les centaines d'entités testés, y compris des entités identiques (`STATE`: `0`, `3`, `4`)

**Comment by Jean-Romain** [comment]
Ok ta réponse me semble raisonnable. On peut imaginer une fonction `post_prod_checks()` qui sort plusieurs métriques de ce style.

**Comment by jfbourdon** [comment]
Voilà une autre idée pour calculer un écart entre deux segments (cette fois-ci avec encore moins de fondements scientifiques). Le long des deux segments, on dépose un nombre égal de points répartis régulièrement en fonction de pourcentages de leur longueur et on mesure ensuite la distance entre chaque paire de points. Je sors ensuite un P50, P90 et P100. Plus c'est élevé, plus y a de chances que quelque chose se soit mal passé.

Si je reprends l'entité de mon premier exemple (OBJECTID `454817` à la position `233`), ça donne ça:
```
p50:  123.4
p90:  183.4
p100: 190.9
```

![ecart2](https://user-images.githubusercontent.com/32580398/143665999-d011fa68-5e26-4ce4-9995-28eab073298f.png)
![ecart3](https://user-images.githubusercontent.com/32580398/143667246-8572ad1e-77be-4dbe-a8ea-1b524d5cc3f7.png)


```r
library(sf)
library(ggplot2)

measure_change2 <- function(road_ori, road_cor, step = 10, graph = FALSE)
{
  n <- ceiling(sf::st_length(road_ori) / step)
  
  pts_extrems <- function(road)
  {
    coords <- sf::st_coordinates(road)[,-3]
    ls_pts <- lapply(c(1, nrow(coords)), function(x) sf::st_point(coords[x,]))
    sf_pts_extrems <- sf::st_sfc(ls_pts, crs = sf::st_crs(road_ori))
  }
  
  
  # Coordonnées des points sur la route d'origine
  sf_pts_ori <- c(pts_extrems(road_ori),
                  sf::st_cast(sf::st_line_sample(road_ori, n), "POINT"))
  
  # Coordonnées des points sur la route corrigée
  sf_pts_cor <- c(pts_extrems(road_cor),
                  sf::st_cast(sf::st_line_sample(road_cor, n), "POINT"))

  
  # Statistiques d'écart
  # Plus les valeurs sont grandes, plus l'écart général
  # entre les deux routes est grand
  dist_step <- as.numeric(diag(sf::st_distance(sf_pts_ori, sf_pts_cor)))
  p <- quantile(dist_step, probs = c(0.5,0.90,1))
  
  
  # Représentation graphique des différences
  if(graph)
  {
    coords_ori <- sf::st_coordinates(sf_pts_ori)
    coords_cor <- sf::st_coordinates(sf_pts_cor)
    
    ls_linestring <- lapply(1:nrow(coords_ori),
                            function(x) {
                              sf::st_linestring(rbind(coords_ori[x,], coords_cor[x,]))
                            })
    
    lines <- sf::st_sfc(ls_linestring, crs = sf::st_crs(road_ori))
    
    print(
      ggplot2::ggplot() +
        ggplot2::geom_sf(data = road_ori, size = 1, color = "red") +
        ggplot2::geom_sf(data = road_cor, size = 1, color = "darkgreen") +
        ggplot2::geom_sf(data = lines, size = 0.5, color = "purple")
    )
    
    df_dist <- data.frame(idx = 1:length(dist_step),
                          distance = dist_step)
    print(
      ggplot2::ggplot(df_dist, aes(x=idx, y=distance)) +
        ggplot2::geom_point() +
        ggplot2::geom_smooth(method = "loess", formula = y ~ x)
    )
    
    message("p50:  ", sprintf("%.1f", p[1]),
            "\np90:  ", sprintf("%.1f", p[2]),
            "\np100: ", sprintf("%.1f", p[3]))
  }
  
  return(p)
}


# Exemple pour quatre segments d'une intersection à partir des
# données de https://github.com/Jean-Romain/MFFProads/files/7600537/dataset.zip
roads_ori <- sf::st_read("dataset.gpkg", "original")
roads_cor <- sf::st_read("dataset.gpkg", "corrected")

for(k in c(3, 30, 233, 314))
{
  measure_change2(roads_ori[k,], roads_cor[k,], graph = TRUE)
}
```
