### ISSUE TITLE
st_snap_line ne fonctionne plus

### ISSUE THREAD

**Issue by Jean-Romain** [Jean-Romain/MFFProads#27]
J'ai peu modifié l'API de snapping pour ne garder qu'une fonction documentée avec données + examples. Sauf que mon example ne fonctionne pas. J'ai peut-être cassé `st_snap_lines2` quelque part. Peux tu regarder et réparer. Je ne suis pas super à l'aise avec ton code je ne trouve pas d'erreur évidente.

**Comment by Jean-Romain** [comment]
Ca c'est fermé tout seul mais le problème est pas résolu puisque l'exemple ne marche toujours pas. Les données ne sont pas bonnes

**Comment by jfbourdon** [comment]
Tu es trop rapide, j'avais pas encore pousser la mise à jour pour fichiers d'exemple :)

**Comment by Jean-Romain** [comment]
La prochaine fois fait un PR avec tout d'un coup haha :wink:. Merci d'avoir corrigé
