### ISSUE TITLE
st_check_crossings exemple

### ISSUE THREAD

**Issue by Jean-Romain** [Jean-Romain/MFFProads#28]
Je ne comprend pas bien l'exemple dans `st_check_crossings`. 

1. Le reseau à l'air valide je ne comprend pas le problème qui est détecté
2. La fonction retourne 3 fois le même point.

**Comment by jfbourdon** [comment]
La représentation graphique n'est pas la meilleure.  Le réseau a l'air valide, mais ne l'est justement pas. L'intersection du haut (avec trois chemins) n'est pas correctement connectée, les trois se croisent, ce qui retourne trois points (similaires, mais pas identiques):
![image](https://user-images.githubusercontent.com/32580398/149975703-8124c3e3-a35f-4a4f-bbf6-ad38069e2dfc.png)

L'intersection du bas n'est pas valide non plus. Les seggments ne se croisent pas, mais sont suffisamment proches pour laisser croire qu'ils font partie de la même jonction. Ce cas est détecté avec `st_check_junctions`
![image](https://user-images.githubusercontent.com/32580398/149976322-401f15d2-5d0e-472b-bb11-b7d934d5f55b.png)

**Comment by Jean-Romain** [comment]
Oui ok je devais pas être super focus quand j'ai posé cette question :wink:
