### ISSUE TITLE
Avertissement systématique "points do not belong in the raster"

### ISSUE THREAD

**Issue by jfbourdon** [Jean-Romain/MFFProads#36]
Depuis un bout de temps (depuis que j'utilise lidR 4.0.0 je crois), lorsque j'utilise `measure_road` j'ai systématiquement un avertissement du genre `68589 points do not belong in the raster. Nearest neighbor was used to assign a value.`. Le résultat est bon toutefois. C'est reproductible avec les fichiers d'exemple:

```r
dir  <- system.file("extdata", "", package="MFFProads")
road <- system.file("extdata", "road_971487.gpkg", package="MFFProads")
dtm  <- system.file("extdata", "dtm_1m.tif", package="MFFProads")
ctg  <- readLAScatalog(dir)
road <- st_read(road, "original", quiet = TRUE)
dtm  <- raster(dtm)
crs(dtm) <- crs(road)

res <- measure_road(ctg, road, dtm)
# Warning message:
# 68589 points do not belong in the raster. Nearest neighbor was used to assign a value.
```

**Comment by Jean-Romain** [comment]
Oui je sais il faut que je regarde ca de plus près mais c'est un peu compliqué à aller chercher.
