### ISSUE TITLE
# inherits(x, "sfc_LINESTRING") is not TRUE

### ISSUE THREAD

**Issue by Jean-Romain** [Jean-Romain/MFFProads#4]
@jfbourdon 

```r
library(MFFProads)
library(lidR)
library(sf)
library(raster)

setwd("Y:/Developpement/Chemins_forestiers/Tests_repositionnement/31P14NE")
path_laz <- getwd()
path_road <- "line.gpkg"
path_dtm <- "dtm.tif"

ctg  <- readLAScatalog(path_laz)
road <- st_read(path_road, quiet = TRUE)
dtm  <- raster(path_dtm)
crs(dtm) <- crs(road)

res <- measure_road(ctg, road, dtm)

#> Error in sf::st_line_sample(road, sample = at) : 
#> inherits(x, "sfc_LINESTRING") is not TRUE
```

https://transfert.mffp.gouv.qc.ca/?ShareToken=A62153A4C75F9B2C1F750EEF2619D50C6D0D656D

Trois autres cas:

https://transfert.mffp.gouv.qc.ca/?ShareToken=3B519DFB833D317AB98102F0DF557BEB432CC75E

**Comment by Jean-Romain** [comment]
```r
road <- st_read(path_road, quiet = TRUE)
poly1 <- sf::st_buffer(road, 80, endCapStyle = "FLAT")
poly2 <- sf::st_buffer(road, 80)

plot(sf::st_geometry(poly2))
plot(st_geometry(road), add=TRUE, col = "blue", lwd = 2)
plot(sf::st_geometry(poly1), add = T, border = "red")
```

![Rplot jpeg](https://user-images.githubusercontent.com/3872279/139717206-8cddd391-6ec8-4b0a-b295-2b429bb12901.png)

**Comment by jfbourdon** [comment]
Même exemple mais légèrement retravaillé pour donner un cas se terminant avec succès et un autre avec l'erreur.
https://transfert.mffp.gouv.qc.ca/?ShareToken=024C0903AABB5147FDA3EC51004B43FC9A2BCA65

```r
library(MFFProads)
library(lidR)
library(sf)
library(raster)

path_laz <- "point_cloud.laz"
path_roads <- "lines.gpkg"
path_dtm <- "dtm.tif"

road_good <- st_read(path_roads, "good")
road_bad <- st_read(path_roads, "bad")
ctg  <- readLAScatalog(path_laz)
dtm  <- raster(path_dtm)
crs(dtm) <- crs(road_good)

measure_road(ctg, road_good, dtm)  # Succès
measure_road(ctg, road_bad, dtm)  # Erreur
```

La seule différence entre les deux lignes en entrée est le déplacement horizontal d'un sommet sur 1.6 m environ.
En rouge la ligne causant une erreur et en vert la ligne n'en causant pas.
![difference](https://user-images.githubusercontent.com/32580398/139724375-5f7b78eb-c6f8-43fa-806c-9099c1fc29ea.png)

**Comment by Jean-Romain** [comment]
Bon j'ai reglé le problème. Ici la route est trouvée 3 (problement n'existant plus). Donc la géométrie d'origine est préservée même si la géométrie trouvée était la bonne.

Cependant je ne suis pas sûr des effets de ma modificatition à grande echelle et je suis pas mal certain qu'on va perdre un petit peu de précision sur le début des routes.

```r
library(MFFProads)
library(lidR)
library(sf)
library(raster)

setwd("~/Téléchargements/mffp issue 4/erreur1/")
path_laz <- getwd()
path_road <- "line.gpkg"
path_dtm <- "dtm.tif"


ctg  <- readLAScatalog(path_laz)
road <- st_read(path_road, quiet = TRUE)
poly1 <- sf::st_buffer(road, param$extraction$road_buffer/2, endCapStyle = "FLAT")
dtm  <- raster(path_dtm)
crs(dtm) <- crs(road)

options(MFFProads.debug.finding = TRUE)
options(MFFProads.debug.measuring = TRUE)
options(MFFProads.debug.metrics = TRUE)
res <- measure_road(ctg, road, dtm)
```

**Comment by jfbourdon** [comment]
Finalement le problème n'est pas complètement parti, en fait il semble avoir été déplacé, j'ai trois cas qui sont en erreur sur c6155e5, mais qui ne le sont pas sur 36815f2, donc avant ta patch.
https://transfert.mffp.gouv.qc.ca/?ShareToken=E86E76A1017DAAFCE6E288E3E5519AC62C2CA906

**Comment by Jean-Romain** [comment]
Ces trois cas vont être difficile à corriger. Faut que je réflechisse

![Rplot03](https://user-images.githubusercontent.com/3872279/140794065-6e7ddf61-f13e-41d0-9b96-adff151a5430.jpeg)
![Rplot02](https://user-images.githubusercontent.com/3872279/140794071-869658ad-ce36-4ef6-b62b-a59f6dd049bb.jpeg)
![Rplot](https://user-images.githubusercontent.com/3872279/140794074-55530002-3314-488a-85bc-2229c75db1d3.jpeg)

**Comment by Jean-Romain** [comment]
Bon c'est une histoire de compromis. Je ne peux pas debugger tous les cas spéciaux. Là l n'y a plus de bug

Là la route disparait clairement. Mais l'algo est prévu pour aller jusqu'au bout et il y  arrive donc il y va.

![Rplot03](https://user-images.githubusercontent.com/3872279/140816243-db0fb464-91d0-422c-8fe4-197247dd172d.jpeg)

Là les bouts de route sont tellement proches que le plus simple c'est aller tout droit quelque soit la conductivité non nulle. Solution facile: reduire le buffer

![Rplot02](https://user-images.githubusercontent.com/3872279/140816247-3644c294-89c6-439c-8311-3137242d72cf.jpeg)

Bien sauvé mais avec un warning quand même

```
Angles above 90 degrees at the begining of the input road. This is weird and may lead to invalid outputs.
```
![Rplot01](https://user-images.githubusercontent.com/3872279/140816250-cb074bd1-0c9d-4b16-8ceb-e9083ec41885.jpeg)

J'ai pas de solution pour celui là. Enfin si mais ca implique des algos qui n'existent pas. Le problème du plus court chemin c'est quíl optimise la somme. On voudrait optimiser la moyenne mais ca n'existe pas à ma connaissance

![Rplot](https://user-images.githubusercontent.com/3872279/140816252-b7a4524c-d863-4e4d-af0e-900692352051.jpeg)

**Comment by jfbourdon** [comment]
Ça me semble bon maintenant effectivement. Les avertissements supplémentaires permettent d'isoler les cas. Je me demande toutefois si un avertissement supplémentaire ne devrait pas être émit si l'une des extrémités de la route corrigée part/arrive à l'un des bouts des _caps_ car si c'est le cas, il y a probablement quelque chose de louche. Ça permettrait de capter des cas comme celui de ton tout premier et tout dernier exemple.
