### ISSUE TITLE
In max(sdZ, na.rm = T) : no non-missing arguments to max; returning -Inf

### ISSUE THREAD

**Issue by jfbourdon** [Jean-Romain/MFFProads#5]
L'avertissement _In max(sdZ, na.rm = T) : no non-missing arguments to max; returning -Inf_ est parfois soulevé. Mon impression est que certaines statistiques liées au nuage de points sont incomplètes en raison d'une trop faible densité de points dans certains profiles. Dans ce cas-ci, la proximité de la route avec un lac y est certainement pour quelque chose.

Ma suggestion serait de conserver un avertissement, mais de le spécifier un peu plus si la cause est trouvée (ex: _Extraction precision may suffer due to low point density relative to profile resolution._) Le message pourrait aussi n'être retourné qu'une seule fois par entité.

Données: https://transfert.mffp.gouv.qc.ca/?ShareToken=D12166D6606730B0807096B7A1B8CE354F2BDA8A

```r
library(MFFProads)
library(lidR)
library(sf)
library(raster)

path_laz <- "point_cloud.laz"
path_roads <- "lines.gpkg"
path_dtm <- "dtm.tif"

roads <- st_read(path_roads)
ctg  <- readLAScatalog(path_laz)
dtm  <- raster(path_dtm)
crs(dtm) <- crs(roads)

measure_road(ctg, road[1,], dtm)  # Normal, no warnings
measure_road(ctg, road[2,], dtm)  # In max(sdZ, na.rm = T) : no non-missing arguments to max; returning -Inf
```

**Comment by Jean-Romain** [comment]
En fait le problème est hyper dur a trouver parce qu'il vient du package raster quand on lui assigne que des NAs. Et la difficulté c'est que le warning ne survient pas quand on roule le code dans l'environnement global. Il n'apparait qui si on le roule dans un environnement. En gros si tu fais:

```r
raster[] <- NA
```
Tu as ce warning... dans certain cas... mais pas dans les cas où tu peux debugger. C'est donc ultra difficile a reproduire (car non reproductible justement). Ne me demande pas pourquoi. Bref ce warning de `raster` est une plaie avec laquel je me suis souvent battu. La  bonne nouvelle justemement c'est que je me suis souvent battu avec déjà

**Comment by Jean-Romain** [comment]
Normalement c'est corrigé. Une histoire de NA et d'interpolation de NA

**Comment by Jean-Romain** [comment]
Notes que cette route est mal trouvé a cause du lac. Comme je l'ai expliqué sans la couche hydro et sans classification `water` le meilleur chemin c'est souvent les lac et les rivière. Avec la couche hydro je suis presqie sûr que ca passe. Je vais essayer.

**Comment by Jean-Romain** [comment]
Je confirme

Avec la couche hydro
![Rplot](https://user-images.githubusercontent.com/3872279/139873800-7a05ea5e-5318-4da5-a16c-40db9d3daf66.jpeg)

Sans la couche hydro
![Rplot01](https://user-images.githubusercontent.com/3872279/139873835-3ee46e82-0463-4204-9f70-5613236698a1.jpeg)
