### ISSUE TITLE
Nom de package plus générique?

### ISSUE THREAD

**Issue by jfbourdon** [Jean-Romain/MFFProads#7]
Considérant qu'il n'est pas improbable que les fonctions de ce package soient utilisées et même bonifiées en-dehors du Ministère des Forêts, de la Faune et des Parcs, je demande s'il ne serait pas approprié de changer le nom du package pour quelque chose de plus générique (ex: _forestRoads_, _lidarTracks_). La variable de paramètres `mffproads_default_parameters` devrait aussi être modifiée.

En fait, est-ce que les fonctions de ce package pourraient se retrouver dans `lidRplugins` ? On y trouve déjà `delineate_lakes()` pouvant servir à la classification des points d'eau de même que la série de fonctions liées aux lignes de transport d'énergie pour la classification. Comme il existe aussi la classe 11 pour les points _Road Surface_, la fonction `measure_road()` y a peut-être sa place aussi.

Il y a certainement d'autres considérations à prendre en compte, mais je dis que ce fasse travail aura peut-être plus de chances de faire des petits en étant intégré à `lidRplugins` qu'en étant un projet indépendant.

**Comment by Jean-Romain** [comment]
Je suis un peu tanné de tout mettre un vrac dans `lidRplugins` avec toujours plus de dépendances. Pour l'instant dans ce package il y a bcp de code, (et pas mal de bugs) je le laisse indépendant de `lidRplugins`. On verra plus tard. Quant au nom avec `MFFP` c'est pas forcément définitif. Moi je m'en fiche. C'était pour souligner et rappeler que c'est un projet pour vous avec votre financement.

**Comment by jfbourdon** [comment]
Je me doutais bien que le problème des dépendances et de stabilité à long terme étaient des enjeux. Peut-être que `lidRplugins` devrait ne contenir que des fonctions expérimentales pouvant être utilisées par d'autres fonctions de `lidR`. À ce compte, c'est peut-être justement que les fonctions de classification de lacs et des lignes de transport d'énergie qui devraient se trouver ailleurs.

Quant au nom de ce package-ci, je te reviendrai éventuellement avec quelque chose.

**Comment by Jean-Romain** [comment]
> Peut-être que lidRplugins devrait ne contenir que des fonctions expérimentales pouvant être utilisées par d'autres fonctions de lidR

C'est exactement ca. Mais bon a force de mettre des truc expérimentaux ca devient le bazar. Je ne m'assure presque jamais de checker si `lidRplugins` fonctionne toujours bien alors bon...

> À ce compte, c'est peut-être justement que les fonctions de classification de lacs et des lignes de transport d'énergie qui devraient se trouver ailleurs.

Exact ça ferait sens. En attendant elle sont là où elles sont. Peut être que `lidRplugins` pourrait être un metapackage avec des dépendances vers des trucs du genre `lidRwire`, `lidRroads`, `lidRtrees`. En ce moment je bosse sur la v4 de lidR (gros chantier) + MFFProads et j'ai vraiment pas le temps de réfléchir à ça en plus. Un jour je mettrais ça au propre.

**Comment by Jean-Romain** [comment]
Je vais créer une organisation `r-lidar` a la facon de `r-spatial` ou `r-lib`. `MFFProad` sera renommé `lidRplugins.roads` et `lidRplugins` sera splité en plusieur sous package `lidRplugins.trees`, `lidRplugins.wires` etc.
