### ISSUE TITLE
Documentation des métriques

### ISSUE THREAD

**Issue by jfbourdon** [Jean-Romain/MFFProads#8]
D'emblée, je me doute que ça viendra plus tard. Ce n'est pas pressant.

Les métriques _road width_, _drivable width_, _right of way_, _% above 0.5_, _% above 2_, _shoulders_, _sinuosity_, _score_ et _state_ sont générés pour chaque route évaluée, toutefois, ce qu'ils représentent n'est présentement pas défini à l'exception de _state_. Avoir simplement une description d'une ligne pour chaque métrique directement dans la documentation de la fonction `measure_road()` serait bien, mais si en plus on peut avoir droit à une vignette avec des représentations graphiques ce serait le comble!

**Comment by Jean-Romain** [comment]
Oui et si ce n'est pas fait c'est que pour l'instant ce n'est pas définitif. 

> road width, drivable width, right of way, score, state, sinuosity

Ca on garde c'est sur

> % above 0.5, % above 2, shoulders,

Ca n'est utile que pour evaluer *state*. C'est dans l'output pour debugger, je ne suis pas sur de garder

> score_conductivity, score_shoulders, score_vegetation, score_drivable

Pas dans l'output et j'hesite à les mettre

**Comment by jfbourdon** [comment]
Qu'est-ce que _right of way_ est sensé représenté, car sur plus de 600 entités, la valeur est toujours nulle.

J'avais oublié _conductivity_ aussi comme métrique qui est présentement sorti. J'imagine que tu le mets au même niveau que les _% above_ et _shoulders_.

Concernant les scores individuels, je suis indécis à savoir si j'aimerais les avoir ou pas. Y a-t-il parfois des écarts importants entre les scores ou bien est-ce qu'ils ont des valeurs assez proches pour un même segment? Si c'est le cas, _score_ sera probablement toujours suffisant. Je ne nous vois pas aller décortiquer aussi profondément. Nos requêtes pour la validation risque surtout de se concentrer sur _drivable width_, _score_ et _state_.

> idealement ca sera plutot un article

On va pas s'opposer à ça non plus! Faire une vignette à partir de ton article pourra alors faire partie d'un exercice de Markdown pour moi.
